### ISSUE TITLE
Cant Install (No Trusted Certificate Found)

### ISSUE THREAD

**Issue by ghost** [ThatWeirdAndrew/GentooWSL#3]
I My self spent 5 hr search and trying to troubleshoot but i cant get this trusted on my computer please somebody help me
![Screenshot 2021-09-26 124307](https://user-images.githubusercontent.com/79795639/134797696-1122cd2b-fb19-44d6-85d8-1a6aad5fe705.png)

**Comment by ghost** [comment]
please someone provide some good documentation next time

**Comment by imaandrew** [comment]
To install the appxbundle, you need to also install the certificate into a trusted store because it's a self-signed certificate so Windows doesn't automatically trust it. You can download the certificate from the releases page and instructions for installing it can be found [here](https://wsldl-pg.github.io/ArchW-docs/Install-Certificate/). Really sorry about the lack of documentation, I'll work on that this week.

**Comment by ghost** [comment]
Thank you so much
